# Generated by Django 4.1.4 on 2024-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/meep_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
